site_name: Enrichment analysis
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Materials: materials.md
    - Exercises: exercises.md
    - Bonus code: bonus_code.md
    - Useful links: links.md

theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg
  features:
    - content.code.copy

# Repository
repo_name: sib-swiss/enrichment-analysis-training
repo_url: https://github.com/sib-swiss/enrichment-analysis-training

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/consent.js
  
extra:
  version:
    provider: mike
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our trainig material and whether users
      find what they're searching for. With your consent, you're helping us to
      make our training material better.
    cookies:
      matomo: Matomo Analytics
  
plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      version_selector: true